// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using wedding_planner.Models;

namespace wedding_planner.Migrations
{
    [DbContext(typeof(WeddingContext))]
    partial class WeddingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("wedding_planner.Models.RSVP", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<int>("UserID");

                    b.Property<int>("WeddingID");

                    b.HasKey("ID");

                    b.ToTable("RSVPS");
                });

            modelBuilder.Entity("wedding_planner.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<int?>("WeddingID");

                    b.HasKey("ID");

                    b.HasIndex("WeddingID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("wedding_planner.Models.Wedding", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<int>("UserID");

                    b.Property<string>("WedderOne");

                    b.Property<string>("WedderTwo");

                    b.Property<string>("WeddingAddress");

                    b.Property<DateTime?>("WeddingDate");

                    b.HasKey("ID");

                    b.ToTable("Weddings");
                });

            modelBuilder.Entity("wedding_planner.Models.User", b =>
                {
                    b.HasOne("wedding_planner.Models.Wedding")
                        .WithMany("Guests")
                        .HasForeignKey("WeddingID");
                });
#pragma warning restore 612, 618
        }
    }
}
